name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version from Project File
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' RecipeApp/RecipeApp.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Application
        run: dotnet publish RecipeApp/RecipeApp.csproj -c Release -o publish -r win-x64 --self-contained true

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Create Velopack Release
        run: |
          vpk pack --channel win --packDir publish --baseUrl https://github.com/${{ github.repository }}/releases/download/v${{ steps.get-version.outputs.version }} --version ${{ steps.get-version.outputs.version }} --exe RecipeApp.exe
          
      - name: Upload to GitHub Releases
        run: |
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --publish --releaseName "RecipeApp ${{ steps.get-version.outputs.version }}" --tag v${{ steps.get-version.outputs.version }} --path ./Releases
