name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Package
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet publish RecipeApp/RecipeApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o publish

      - name: Install Velopack CLI
        run: dotnet tool install --global Velopack.Cli

      - name: Package with Velopack
        run: |
          velopack pack --input publish `
                        --platform win `
                        --version "${{ github.ref_name }}" `
                        --output artifacts `
                        --sign=false

      - name: Upload Velopack Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: velopack-artifacts
          path: artifacts

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: velopack-artifacts
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
